apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: myticketing-dev-335414
  artifacts:
    - image: preethamlv/auth
    # - image: asia.gcr.io/myticketing-dev-335414/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: preethamlv/client
    # - image: asia.gcr.io/myticketing-dev-335414/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: preethamlv/tickets
    # - image: asia.gcr.io/myticketing-dev-335414/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: preethamlv/orders
    # - image: asia.gcr.io/myticketing-dev-335414/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: preethamlv/expiration
    # - image: asia.gcr.io/myticketing-dev-335414/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: preethamlv/payments
    # - image: asia.gcr.io/myticketing-dev-335414/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
